use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .expect("mux-compiler should have a parent directory");

    // Set up git hooks path for development
    if env::var("CI").is_err() {
        let _ = set_git_hooks_dir::setup(workspace_root.join(".github/hooks"), workspace_root);
    }

    let profile = if env::var("CARGO_PROFILE_RELEASE").is_ok() {
        "release"
    } else {
        "debug"
    };

    let target_dir = env::var("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| workspace_root.join("target"));

    let debug_path = target_dir.join("debug");
    let release_path = target_dir.join("release");
    let profile_path = target_dir.join(profile);

    let (static_lib, dynamic_lib) =
        detect_runtime_library(workspace_root, &debug_path, &release_path, &profile_path);

    println!(
        "cargo:rustc-env=MUX_RUNTIME_STATIC={}",
        static_lib.display()
    );
    println!(
        "cargo:rustc-env=MUX_RUNTIME_DYNAMIC={}",
        dynamic_lib.display()
    );
    println!("cargo:rustc-env=MUX_RUNTIME_DIR={}", profile_path.display());

    generate_embedded_std_sources(&manifest_dir);
}

fn generate_embedded_std_sources(manifest_dir: &Path) {
    let std_dir = manifest_dir.join("std");
    println!("cargo:rerun-if-changed={}", std_dir.display());

    let mut std_files = Vec::new();
    collect_mux_files(&std_dir, &std_dir, &mut std_files);
    std_files.sort_by(|a, b| a.0.cmp(&b.0));

    let out_file = manifest_dir.join("src").join("embedded_std.rs");

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs. Do not edit manually.\n");
    generated.push_str("use std::collections::HashMap;\n");
    generated.push_str("use std::sync::OnceLock;\n\n");
    generated.push_str("pub fn embedded_std_sources() -> &'static HashMap<String, String> {\n");
    generated
        .push_str("    static SOURCES: OnceLock<HashMap<String, String>> = OnceLock::new();\n");
    generated.push_str("    SOURCES.get_or_init(|| {\n");
    generated.push_str("        let mut m = HashMap::new();\n");

    for (module_key, relative_path) in std_files {
        let include_path = format!("../std/{}", relative_path);
        generated.push_str(&format!(
            "        m.insert(\"{}\".to_string(), include_str!(\"{}\").to_string());\n",
            module_key, include_path
        ));
    }

    generated.push_str("        m\n");
    generated.push_str("    })\n");
    generated.push_str("}\n");

    fs::write(&out_file, generated).expect("failed to write src/embedded_std.rs");
}

fn collect_mux_files(base: &Path, current: &Path, out: &mut Vec<(String, String)>) {
    let entries = match fs::read_dir(current) {
        Ok(entries) => entries,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_mux_files(base, &path, out);
            continue;
        }

        if path.extension().is_none_or(|ext| ext != "mux") {
            continue;
        }

        let Ok(relative) = path.strip_prefix(base) else {
            continue;
        };

        let relative_str = relative.to_string_lossy().replace('\\', "/");
        let mut module = relative_str
            .trim_end_matches(".mux")
            .replace('/', ".")
            .to_string();
        if !module.starts_with("std.") {
            module = format!("std.{}", module);
        }

        out.push((module.clone(), relative_str.clone()));

        if let Some(short) = module.strip_prefix("std.") {
            out.push((short.to_string(), relative_str));
        }
    }
}

#[cfg(target_family = "unix")]
fn detect_runtime_library(
    workspace_root: &Path,
    debug_path: &Path,
    release_path: &Path,
    profile_path: &Path,
) -> (PathBuf, PathBuf) {
    let candidates: Vec<(PathBuf, &str)> = vec![
        (
            profile_path.to_path_buf(),
            "profile-specific (release or debug)",
        ),
        (release_path.to_path_buf(), "release"),
        (debug_path.to_path_buf(), "debug"),
        (
            workspace_root.join("target").join("release"),
            "workspace/target/release",
        ),
        (
            workspace_root.join("target").join("debug"),
            "workspace/target/debug",
        ),
    ];

    for (path, _) in &candidates {
        let static_lib = path.join("libmux_runtime.a");
        let dynamic_lib = path.join("libmux_runtime.so");
        if static_lib.exists() || dynamic_lib.exists() {
            println!("cargo:warning=Found libmux_runtime in {}", path.display());
            return (static_lib, dynamic_lib);
        }
    }

    let static_lib = profile_path.join("libmux_runtime.a");
    let dynamic_lib = profile_path.join("libmux_runtime.so");

    if !static_lib.exists() && !dynamic_lib.exists() {
        println!(
            "cargo:warning=Could not find libmux_runtime yet. Expected locations:\n\
             - {} (profile-specific)\n\
             - {}\n\
             - {}\n\
             - {}\n\
             - {}\n\
             The mux CLI will request a runtime build if needed.",
            profile_path.display(),
            release_path.display(),
            debug_path.display(),
            workspace_root.join("target").join("release").display(),
            workspace_root.join("target").join("debug").display()
        );
    }

    (static_lib, dynamic_lib)
}

#[cfg(target_family = "windows")]
fn detect_runtime_library(
    workspace_root: &Path,
    debug_path: &Path,
    release_path: &Path,
    profile_path: &Path,
) -> (PathBuf, PathBuf) {
    let check_path = |p: &Path| -> (PathBuf, PathBuf) {
        let static_lib = p.join("mux_runtime.lib");
        let dynamic_lib = p.join("mux_runtime.dll");
        if static_lib.exists() {
            (static_lib, dynamic_lib)
        } else if dynamic_lib.exists() {
            (static_lib, dynamic_lib)
        } else {
            (static_lib, dynamic_lib)
        }
    };

    let candidates: Vec<(PathBuf, &str)> = vec![
        (
            profile_path.to_path_buf(),
            "profile-specific (release or debug)",
        ),
        (release_path.to_path_buf(), "release"),
        (debug_path.to_path_buf(), "debug"),
        (
            workspace_root.join("target").join("release"),
            "workspace/target/release",
        ),
        (
            workspace_root.join("target").join("debug"),
            "workspace/target/debug",
        ),
    ];

    for (path, description) in &candidates {
        let (static_lib, dynamic_lib) = check_path(path);
        if static_lib.exists() || dynamic_lib.exists() {
            println!(
                "cargo:warning=Found mux_runtime in {} (checking {})",
                path.display(),
                description
            );
            return (static_lib, dynamic_lib);
        }
    }

    let static_lib = profile_path.join("mux_runtime.lib");
    let dynamic_lib = profile_path.join("mux_runtime.dll");

    if !static_lib.exists() && !dynamic_lib.exists() {
        println!(
            "cargo:warning=Could not find mux_runtime yet. Expected locations:\n\
             - {} (profile-specific)\n\
             - {}\n\
             - {}\n\
             - {}\n\
             - {}\n\
             The mux CLI will request a runtime build if needed.",
            profile_path.display(),
            release_path.display(),
            debug_path.display(),
            workspace_root.join("target").join("release").display(),
            workspace_root.join("target").join("debug").display()
        );
    }

    (static_lib, dynamic_lib)
}
