// @generated by build.rs. Do not edit manually.
use std::collections::HashMap;
use std::sync::OnceLock;

pub fn embedded_std_sources() -> &'static HashMap<String, String> {
    static SOURCES: OnceLock<HashMap<String, String>> = OnceLock::new();
    SOURCES.get_or_init(|| {
        let mut m = HashMap::new();
        m.insert(
            "dsa.algorithm".to_string(),
            include_str!("../std/dsa/algorithm.mux").to_string(),
        );
        m.insert(
            "dsa.bintree".to_string(),
            include_str!("../std/dsa/bintree.mux").to_string(),
        );
        m.insert(
            "dsa.collection".to_string(),
            include_str!("../std/dsa/collection.mux").to_string(),
        );
        m.insert(
            "dsa.graph".to_string(),
            include_str!("../std/dsa/graph.mux").to_string(),
        );
        m.insert(
            "dsa.heap".to_string(),
            include_str!("../std/dsa/heap.mux").to_string(),
        );
        m.insert(
            "dsa.queue".to_string(),
            include_str!("../std/dsa/queue.mux").to_string(),
        );
        m.insert(
            "dsa.stack".to_string(),
            include_str!("../std/dsa/stack.mux").to_string(),
        );
        m.insert(
            "std.dsa.algorithm".to_string(),
            include_str!("../std/dsa/algorithm.mux").to_string(),
        );
        m.insert(
            "std.dsa.bintree".to_string(),
            include_str!("../std/dsa/bintree.mux").to_string(),
        );
        m.insert(
            "std.dsa.collection".to_string(),
            include_str!("../std/dsa/collection.mux").to_string(),
        );
        m.insert(
            "std.dsa.graph".to_string(),
            include_str!("../std/dsa/graph.mux").to_string(),
        );
        m.insert(
            "std.dsa.heap".to_string(),
            include_str!("../std/dsa/heap.mux").to_string(),
        );
        m.insert(
            "std.dsa.queue".to_string(),
            include_str!("../std/dsa/queue.mux").to_string(),
        );
        m.insert(
            "std.dsa.stack".to_string(),
            include_str!("../std/dsa/stack.mux").to_string(),
        );
        m.insert(
            "std.test".to_string(),
            include_str!("../std/test.mux").to_string(),
        );
        m.insert(
            "test".to_string(),
            include_str!("../std/test.mux").to_string(),
        );
        m
    })
}
